FROM alpine/git as repo
WORKDIR /app
run git clone --single-branch -b custom https://github.com/IvanYankovskiy/Factory_control.git

FROM maven:3.9.9-amazoncorretto-21 as build
WORKDIR /app
COPY --from=repo /app/Factory_control /app
RUN mvn clean install -DskipTests

FROM amazoncorretto:21.0.4-alpine3.18 as app
EXPOSE 8080

WORKDIR root/
COPY --from=build /app /root
RUN mv target/control-*.jar target/application.jar
ENTRYPOINT ["java", "-server", "-Xms256M", "-Xmx256M",\
            "-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=dump.hprof", "-Djava.security.egd=/dev/zrandom",\
            "-jar", "/root/target/application.jar"]
